# Generated by Django 6.0.1 on 2026-02-07 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=300)),
                ('open_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='ageRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Возрастное ограничение',
                'verbose_name_plural': 'Возрастные ограничения',
            },
        ),
        migrations.CreateModel(
            name='organisator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=20)),
                ('info', models.TextField(null=True)),
                ('idOrganisator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Организатор',
                'verbose_name_plural': 'Организаторы',
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=60)),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('post_date', models.DateField(verbose_name='Дата публикации')),
                ('participants', models.IntegerField()),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.adress')),
                ('ageRestrictions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agerestrictions')),
                ('organisator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisator')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
