# Generated by Django 6.0.1 on 2026-05-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_eventtype_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
