# Generated by Django 6.0.1 on 2026-02-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
