# Generated by Django 6.0.1 on 2026-02-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_event_end_event_event_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='adress',
        ),
        migrations.AddField(
            model_name='adress',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='home',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='street',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
