# Generated by Django 6.0.1 on 2026-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='event_documents/', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='event',
            name='verified',
            field=models.CharField(choices=[('unverified', 'На проверке'), ('approved', 'Одобрено'), ('denied', 'Отказано')], default='unverified', max_length=20, verbose_name='Статус верификации'),
        ),
    ]
