# Generated by Django 6.0.1 on 2026-05-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_document_event_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment_from_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='сomment_for_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
